Numero de arboles en mal estado comparando parque y calle
numero de arboles de cada especie ordenados de mas a menos
media de altura y ancho y extension por especie de arbol
que especie es mas comun en las calles y en los parques

wikidata: sacar fotos para cada arbol